import groovy.json.JsonOutput
import groovy.json.JsonSlurper

plugins {
    id "idea"

    id "net.minecraftforge.gradle" version "[6.0,6.2)"

    // https://parchmentmc.org/docs/getting-started
    id "org.parchmentmc.librarian.forgegradle" version "1.+" // docs for minecraft code

    // https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge
    id "org.spongepowered.mixin" version "0.7.+"
}

java {
    // Minecraft 1.18+ uses Java 17
    sourceCompatibility JavaVersion.VERSION_17

    withSourcesJar()
}

// Use the UTF-8 charset for java compilation
tasks.withType(JavaCompile).configureEach {
    options.encoding "UTF-8"
}

version = "0.45.2-1.16.5"
group = "com.mrcrayfish"
archivesBaseName = "vehicle-mod"

minecraft {
    mappings mapping_channel, mapping_version

    accessTransformer = file "src/main/resources/META-INF/accesstransformer.cfg"

    // Copy the files from "processResources" to the IDE's resource output directories
    copyIdeResources = true

    runs {
        configureEach {
            mods {
                vehicle {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
        server {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
        data {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            args '--mod', 'vehicle', '--all', '--output', file('src/generated/resources/')
        }
    }
}

repositories {
    maven {
        url = "https://www.cursemaven.com"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:$minecraft_version-$forge_version"

    annotationProcessor "org.spongepowered:mixin:$mixin_version:processor"

    implementation fg.deobf("curse.maven:framework-549225:$framework_id")
    implementation fg.deobf("curse.maven:controllable-317269:$controllable_id")
    implementation fg.deobf("curse.maven:configured-457570:$configured_id")
    implementation fg.deobf("curse.maven:catalogue-459701:$catalogue_id")
}

// Include resources generated by datagen
sourceSets.main.resources.srcDir "src/generated/resources"

processResources {
    doLast {
        fileTree(dir: outputs.files.asPath, include: "**/*.json").each {
            File file -> file.text = JsonOutput.toJson(new JsonSlurper().parse(file))
        }
    }
}

jar {
    manifest {
        attributes([
            "Specification-Title": "Vehicle Mod",
            "Specification-Vendor": "MrCrayfish",
            "Specification-Version": "1",
            "Implementation-Title": "Vehicle Mod",
            "Implementation-Version": project.version,
            "Implementation-Vendor" : "MrCrayfish",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
