org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

version=0.45.2-1.20.1
group=com.mrcrayfish
archivesBaseName=vehicle-mod

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data
mapping_channel=parchment
mapping_version=2023.08.06-1.20.1

mixin_version=0.8.5

framework_id=6531428
controllable_id=6171424
configured_id=5180900
catalogue_id=6926819
